# Generated by Django 2.0.13 on 2019-06-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop2',
        ),
    ]
